server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: products-service
          uri: http://localhost:8080
          predicates:
            - Path=/products/**
          filters:
            - AddRequestHeader=X-Request-Gateway, SpringCloudGateway
        - id: users-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: orders-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
        - id: payments-service
          uri: http://localhost:8083
          predicates:
            - Path=/payments/**
