version: '3.8'
services:
  products-db:
    image: mysql:latest
    container_name: service-products-db
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_DATABASE: products_db
    ports:
      - "3306:3306"
    volumes:
      - ./init-scripts/products_data.sql:/docker-entrypoint-initdb.d/products_data.sql

  users-db:
    image: mysql:latest
    container_name: service-users-db
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_DATABASE: users_db
    ports:
      - "3307:3306"
    volumes:
      - ./init-scripts/users_data.sql:/docker-entrypoint-initdb.d/users_data.sql

  orders-db:
    image: mysql:latest
    container_name: service-orders-db
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_DATABASE: orders_db
    ports:
      - "3308:3306"
    volumes:
      - ./init-scripts/orders_data.sql:/docker-entrypoint-initdb.d/orders_data.sql

  payments-db:
    image: mysql:latest
    container_name: service-payments-db
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_DATABASE: payments_db
    ports:
      - "3309:3306"
    volumes:
      - ./init-scripts/payments_data.sql:/docker-entrypoint-initdb.d/payments_data.sql

volumes:
  products-db-data:
  users-db-data:
  orders-db-data:
  payments-db-data:
